
name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
        # Instalar PHP y PHPUnit en el runner de GitHub Actions
      - name: Install PHP and PHPUnit
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli php-xml wget unzip
          wget https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit-9.phar
          sudo mv phpunit-9.phar /usr/local/bin/phpunit

      # Verificar si la carpeta `php_app` existe
      - name: Verify php_app directory
        run: |
          if [ -d "php_app" ]; then
            echo "php_app directory exists"
          else
            echo "php_app directory does not exist"
            exit 1
          fi

      # Listar los archivos dentro de `php_app` para verificar estructura
      - name: List php_app contents
        run: |
          ls -R php_app

      # Ejecutar pruebas unitarias antes del despliegue
      - name: Run PHPUnit Tests
        run: |
          cd php_app  
          phpunit --configuration phpunit.xml  # Ejecutar las pruebas

      # Si las se pasa el phpunit, continúa con Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: "us-east-1"

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
